!!python/object:sklearn.pipeline.Pipeline
_sklearn_version: 1.3.1
memory: null
steps:
- !!python/tuple
  - scaler
  - !!python/object:sklearn.preprocessing._data.StandardScaler
    _sklearn_version: 1.3.1
    copy: true
    with_mean: true
    with_std: true
- !!python/tuple
  - poly
  - !!python/object:sklearn.preprocessing._polynomial.PolynomialFeatures
    _sklearn_version: 1.3.1
    degree: 2
    include_bias: true
    interaction_only: false
    order: C
- !!python/tuple
  - pca
  - !!python/object:sklearn.decomposition._pca.PCA
    _sklearn_version: 1.3.1
    copy: true
    iterated_power: auto
    n_components: null
    n_oversamples: 10
    power_iteration_normalizer: auto
    random_state: null
    svd_solver: auto
    tol: 0.0
    whiten: false
- !!python/tuple
  - lasso
  - !!python/object:sklearn.linear_model._coordinate_descent.Lasso
    _sklearn_version: 1.3.1
    alpha: 1.0
    copy_X: true
    fit_intercept: true
    l1_ratio: 1.0
    max_iter: 1000
    positive: false
    precompute: false
    random_state: null
    selection: cyclic
    tol: 0.0001
    warm_start: false
verbose: false
